[package]
name = "rizlium_editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rizlium_render = {path="../rizlium_render"}
font-kit = "*"
bevy_egui = "*"
egui = "0.22"
egui_dock = "*"
strum = { version = "0.25", features = ["derive"] }
# Todo: split x11, wayland and webgl2
bevy = { version = "0.11", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_scene",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_gltf",
    "bevy_render",
    "bevy_sprite",
    "png",
    "hdr",
    "zstd",
    "x11",
    "ktx2",
    "filesystem_watcher",
    "tonemapping_luts",
    "webgl2",
    "wayland"
] }
rizlium_chart ={ path = "../rizlium_chart"}