[package]
name = "rizlium_chart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-easing = "1"
log="0"
snafu="0"
serde = "1.0"
serde_derive = "1.0"
num_enum = "0.6"
enum_dispatch = {version = "*", optional = true}

[dev-dependencies]
serde_json = "*"
static_init = "*"

[features]
default = ["runtime", "editing"]
runtime = []
editing = ["enum_dispatch"]
