[package]
name = "rizlium_chart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-easing = "*"
log="*"
nutype = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
cfg-if = "1.0.0"

[features]
atomic = []
