[package]
name = "rizlium_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
bevy_egui = "*"
bevy-inspector-egui = "*"
# bevy_prototype_lyon = {git = "https://github.com/liquidhelium/bevy_prototype_lyon_rizlium"}
bevy_prototype_lyon = {path = "../../bevy_prototype_lyon_rizlium"}
rizlium_chart = {path="../rizlium_chart",features = ["atomic"]}
mouse_tracking = {package = "bevy_mouse_tracking_plugin", version = "0.6.0"}
