[package]
name = "rizlium_game"
version = "0.2.2"
edition = "2021"

[dependencies]
bevy = { version = "0.16", default-features = false }
bevy_egui = "0.25"
egui = "0.31"
helium_framework = { git = "https://github.com/liquidhelium/helium_framework", features = ["serde"] }
rizlium_render = { path = "../rizlium_render" }
rizlium_project = { path = "../rizlium_project" }
rizlium_audio = { path = "../rizlium_audio" }
rust-i18n = "3"
rizlium_explorer = { path = "../rizlium_explorer" }