[package]
name = "helium_framework"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.18", default-features = false, features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "png",
    "hdr",
    "ktx2",
    "tonemapping_luts",
    "wayland",
    "multi_threaded",
    "bevy_gizmos",
    "std",
    "async_executor",
    "bevy_log"
] }
bevy_egui = "0.39"
egui = "0.33"
egui_dock = "0.18"
egui-notify = "0.21"
snafu = "0.8"
smallvec = "1"
serde = {version = "1", features = ["derive"], optional = true}
rizlium_l10n = { path = "../rizlium_l10n" }
indexmap = "2"
enum_dispatch = "0.3"
variadics_please = "1.1"


[features]
default = ["serde"]
serde = ["egui_dock/serde", "smallvec/serde", "dep:serde"]

# [[example]]
# name = "basic"

# [profile.release]
# codegen-backend = "cranelift"